### ISSUE TITLE
problem in mining_coo

### ISSUE THREAD

**Issue by DesgerMadrigal** [x-actly/Eve-Online-Mining-Bot#28] opened 2024-05-04 07:18 UTC
I have the following error code:
values saved!
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\moi12\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\moi12\OneDrive\Documentos\Eve-Online-Mining-Bot-main\Eve-Online-Mining-Bot-main\main.py", line 31, in start_function
    mining_coo_values = [(int(x.strip()), int(y.strip())) for x, y in (value.split(",") for value in config['POSITIONS']['mining_coo'].split("\n"))]
  File "C:\Users\moi12\OneDrive\Documentos\Eve-Online-Mining-Bot-main\Eve-Online-Mining-Bot-main\main.py", line 31, in <listcomp>
    mining_coo_values = [(int(x.strip()), int(y.strip())) for x, y in (value.split(",") for value in config['POSITIONS']['mining_coo'].split("\n"))]
ValueError: not enough values to unpack (expected 2, got 1)
I have no idea what is causing it, even using the values as they come in config.properties.example, image attachment and code:
`[SETTINGS]
mining_runs = 30
mining_hold = 5000
mining_yield = 3

[POSITIONS]
undock_coo = 1306, 334
clear_cargo_coo = 180, 732
docking_coo = 
target_one_coo = 1210, 502
target_two_coo = 1210, 252
mouse_reset_coo = 737, 847
warp_to_coo = 1115, 711
mining_coo = 1115, 735
	1115, 758
	1115, 783
	1115, 803
	`
	
	
![Captura de pantalla 2024-05-04 011745](https://github.com/x-actly/Eve-Online-Mining-Bot/assets/58780465/99bf18ee-f8ae-4768-a554-951afc296e66)

As soon as I get it fixed I’ll upload the solution

**Comment by DesgerMadrigal** [comment] 2024-05-04 07:21
The solution is in the file: config.properties remove whitespace that is being generated at the end of the document
amazing, hahaha!

**Comment by jarlah** [comment] 2024-05-04 08:04
I have gotten that issue myself. Need to fix it ...

**Comment by jarlah** [comment] 2024-05-04 08:08
Feel free to pick up the new issue i created and fix it if havent done it yet. But set yourself as assigned to the new issue first

**Comment by jarlah** [comment] 2024-05-04 09:47
Dont know why i made new issue. Wanted to change title and add more info ...

**Comment by DesgerMadrigal** [comment] 2024-05-04 22:09
@jarlah  there is also an error that does not give right click in the windows of eve online, I am trying to fix it

**Comment by jarlah** [comment] 2024-05-05 06:30
> @jarlah there is also an error that does not give right click in the windows of eve online, I am trying to fix it

ive been running the current version of the main branch for a long time now and havent seen that issue. But another thing, some of the safe spot right clicking is unnecessary. Should only be needed to move mouse to safe spot and left click for ex.

**Comment by jarlah** [comment] 2024-05-06 07:03
fixed by #42

**Comment by jarlah** [comment] 2024-05-06 07:04
@DesgerMadrigal i made a new issue for the right clicking issue you found, and closed  this as the problem is fixed

**Closed by jarlah** 2024-05-06 07:03 UTC
